# Schema for the configuration files of the Bulma theme.

BULMA_SUBTHEME_MACHINE_NAME.settings:
  type: theme_settings
  label: 'Bulma settings'
  mapping:
    general:
      type: mapping
      label: 'Bulma general settings'
      mapping:
        general.block:
          type: integer
          label: 'Bulma block style'
        general.icon:
          type: integer
          label: 'Use icons'
        general.icon_type:
          type: integer
          label: 'Use default field type icons'
        general.menu:
          type: string
          label: 'Bulma nav menu'
    button:
      type: mapping
      label: 'Bulma buttons'
      mapping:
        button.colorize:
          type: integer
          label: 'Colorize button'
        button.size:
          type: string
          label: 'Button size'
        button.outlined:
          type: integer
          label: 'Outlined button'
        button.inverted:
          type: integer
          label: 'Inverted button'
    elements:
      type: mapping
      label: 'Bulma form elements'
      mapping:
        elements.labels_inline:
          type: integer
          label: 'Horizontal form'
        elements.input_size:
          type: string
          label: 'Form element size'
        elements.labels_rounded:
          type: integer
          label: 'Rounded labels'
        elements.labels_color:
          type: string
          label: 'Labels style'
        elements.labels_size:
          type: string
          label: 'Labels size'
    tabs:
      type: mapping
      label: 'Bulma tabs'
      mapping:
        tabs.position:
          type: string
          label: 'Tabs position'
        tabs.size:
          type: string
          label: 'Tabs size'
        tabs.style:
          type: string
          label: 'Tabs style'
        tabs.fullwidth:
          type: integer
          label: 'Tabs fullwidth'
    table:
      type: mapping
      label: 'Bulma table'
      mapping:
        table.bordered:
          type: integer
          label: 'Bordered'
        table.striped:
          type: integer
          label: 'Striped'
        table.narrow:
          type: integer
          label: 'Narrow'
